### ISSUE TITLE
Testimony history screen

### ISSUE THREAD

**Issue by davidrideout** [CodeforHawaii/kuka#18]
Create a testimony history screen with a list of testimonies the user has made and their potential status.

**Comment by johntimothybailey** [comment]
@davidrideout Isn't this a copy of https://github.com/CodeforHawaii/kuka/issues/13

I started on this work a few weeks back when we discussed it as a option to work on. 

So far, I have made the screen with the forms and the Position Action buttons.

**Comment by davidrideout** [comment]
Not a copy of #13. Just updated the description/title.

**Comment by johnkmzhou** [comment]
Just noticed that the layout needs fixing and functionality needs to be added.

**Comment by johnkmzhou** [comment]
Note that currently, the video has to finish uploading before the testimony data is pushed to Firestore. This means that the uploading status cannot be displayed on the testimony history screen. In the future, this may be a feature that we add.
